### ISSUE TITLE
Wikipedia page disappeared

### ISSUE THREAD

**Issue by hackerb9** [jeffmcneill/beteckna#15]
Somebody deleted the [Beteckna wikipedia entry](https://en.wikipedia.org/wiki/Beteckna) for not being noteworthy. Beteckna seems noteworthy to me as it is the closest in spirit to Futura of the fonts that come with Redhat, Ubuntu, and other GNU/Linux systems. Also, if I remember right, it was one of the first fonts to use the GPL with font-exception. Since the page was deleted using Wikipedia's PROD (proposed deletion for quick, uncontroversial removals), I think all it takes to get it reinstated is for somebody to contest the removal, but I do not know for sure.

**Comment by alexmyczko** [comment]
Meanwhile there's also https://github.com/theleagueof/league-spartan that is a noteworthy Futura spirit like font. That comes with Ubuntu and Debian... https://repology.org/metapackage/fonts:league-spartan/versions

**Comment by jeffmcneill** [comment]
Wikipedia is a cabal https://thewikicabal.com/
